linux-system-roles/nbde_client

tests/tasks/cleanup_test.yml
tests/tests_passphrase_temporary_keyfile.yml

The test needs to copy the original temporary key file to the
managed host to see if it can still be used to unlock.  Check
that the error returned from verify is the error that says
the key did not work.

fix temp pass key test

---

README.md
defaults/main.yml
examples/high_availability.yml
examples/remove_binding.yml
library/nbde_client_clevis.py
tasks/main-clevis.yml
tests/tasks/cleanup_test.yml
tests/tasks/setup_test.yml
tests/tasks/verify_default_key_file.yml
tests/tests_bind_high_availability.yml
tests/tests_key_rotation.yml
tests/tests_passphrase_temporary.yml
tests/tests_passphrase_temporary_keyfile.yml
tests/tests_simple_bind.yml
tests/tests_simple_bind_keyfile.yml
tests/tests_simple_bind_unbind.yml
tests/tests_simple_bind_unbind_keyfile.yml
tests/tests_use_existing_binding.yml
tests/vars/main.yml

use `encryption_key_src` instead of `key_file`
use `encryption_password` instead of `passphrase`
use `password_temporary` instead of `passphrase_temporary`

use consistent tls/crypto parameter naming

---

library/nbde_client_clevis.py

The module parameter name for the list of bindings is just `bindings`
with no `nbde_client_` prefix.
This isn't critical as the module isn't part of the public interface.

The module parameter name is "bindings" with no role prefix

---

.github/workflows/tox.yml
molecule/default/molecule.yml
tests/tasks/setup_test.yml
tests/tasks/verify_default_key_file.yml
tests/tasks/verify_default_passphrase.yml
tests/tasks/verify_unlock_device.yml

Deprecate the use of molecule for linting.  Use tox for ansible-lint.
The next step will be to remove the ansible-lint dependency from
the molecule environments.

use tox for ansible-lint instead of molecule

---

meta/main.yml
tests/vars/RedHat_9.yml
vars/RedHat_9.yml

From now the `rhel-8-y` status is the latest unreleased RHEL-8 and the `rhel-x` status is pre-released RHEL-9.

CI: Add support for RHEL-9

---

library/nbde_client_clevis.py

RHELPLAN-69928  Add a note to each module Doc to indicate it is private
- Adding "WARNING: Do not use this module directly! It is only for role internal use." to nbde_client_clevis module DOCUMENTATION.
- Using suboptions to describe the value of `bindings`.

RHELPLAN-68127 - Collections - Nbde_client - fixing ansible-test errors

---

README.md

Some markdown renderer does not process the file properly if there's no blank line between a header, a table, etc.
E.g.,
```
`nbde_client_bindings` is a list of dictionaries that support the following keys:
| **Name** | **Default/Choices** | **Description** |
|----------|-------------|------|
| `device` | | specifies the path of the ...
```
==>
`+nbde_client_bindings+ is a list of dictionaries that support the following keys: | Name | Default/Choices | Description | |----------|-------------|------| | +device+ | | specifies the path of the ...`.
By adding a blank line between the header/table and the ordinary line, it's processed properly.

README.md - Adding a blank line after nbde_client_bindings

---

vars/CentOS_8.yml
vars/Fedora.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption_security-hardening#configuring-manual-enrollment-of-volumes-using-clevis_configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption
section 9.9 point 5 recommends using dracut -f plus --regenerate-all sometimes the systems can not be booted

add regenerate-all to the dracut command 

---

files/nbde_client-network-flush
files/nbde_client/module-setup.sh
files/nbde_client/nbde_client-hook.sh
tasks/main-clevis.yml
vars/CentOS_7.yml
vars/CentOS_8.yml
vars/CentOS_9.yml
vars/Fedora.yml
vars/RedHat_7.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

The network connection created during the initramfs for unlocking the
device may conflict with the actual system connection later on, when
the system attempts to configure the network as per the regular
configuration, after the boot process has completed.
To prevent this situation, we now deploy a dracut module to disable
autoconnect of the network connectons that are active during the
initramfs.

Add dracut module for disabling autoconnect within initrd

---

files/nbde_client-network-flush
files/nbde_client-network-flush.service
files/nbde_client/nbde_client-hook.sh
tasks/main-clevis.yml

With older dracut, where NetworkManager does not run as a daemon
and with dbus, the dracut module we have will not work to disable
autoconnect for the connections created within the initramfs, which
may be a problem as after the network flush, NM will activate the
connection with the higher priority, and the initramfs connection
may be it.
Some connections are created with negative priority, by e.g. the
Anaconda installer, which may be a problem in this situation. To
work around this issue, we now reset the autoconnect priority of
the connections to zero.

network-flush: reset autoconnect-priority to zero

---

vars/CentOS_7.yml
vars/CentOS_8.yml
vars/CentOS_9.yml
vars/Fedora.yml
vars/RedHat_7.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

In our limited testing, we've found that the appended rd.neednet parameter needs to have proper spacing between the quotes.  I.E.  kernel_cmdline+= " rd.neednet=1 " so that it's properly appended to the kernel command line.  
When using a static IP, if the rd.neednet parameter does not have proper spacing, adapter link does not appear to be brought up.  These commits modify the vars yaml file for each distro to use the spaced out parameter.  Also changes = to += for the append operation.

Sets needed spacing for appended rd.neednet parameter

---

tasks/main-clevis.yml

A bug was introduced in PR [Add default clevis luks askpass unit #79](https://github.com/linux-system-roles/nbde_client/pull/79) which silently fails to configure the clevis askpass unit correctly on RHEL 8.2 and 8.3 with certain versions of the `clevis-systemd` package installed. This PR fixes it by changing the conditional such that if the `clevis-luks-askpass.path` service exists, it is enabled. If it doesn't exist, then a version of `clevis-systemd` that uses templated units is installed, and the unit will be enabled by `dracut`. Tests have been successful with templated, and static `clevis-luks-askpass.path` units.

correct clevis askpass unit conditional

---

tests/collection-requirements.yml
tests/tasks/cleanup_test.yml
tests/tasks/rotate_keys.yml
tests/tasks/setup_test.yml

use fedora.linux_system_roles.nbde_server for tests instead of git
cloning the repo.  Use the `tests/collection-requirements.yml` so
the test infrastructure will install the collection.

use fedora.linux_system_roles.nbde_server for tests

---

CHANGELOG.md

[1.2.8] - 2022-11-29
--------------------
- none
- use fedora.linux_system_roles.nbde_server for tests (#86)
use fedora.linux_system_roles.nbde_server for tests instead of git
cloning the repo.  Use the `tests/collection-requirements.yml` so
the test infrastructure will install the collection.
- none
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

Version 1.2.8 - CHANGELOG.md [citest skip]

---

.github/workflows/woke.yml
CHANGELOG.md
README.md
library/nbde_client_clevis.py
tests/tasks/cleanup_test.yml

Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Clean up non-inclusive words.    
- CHANGELOG.md
- README.md
- library/nbde_client_clevis.py
- tests/tasks/cleanup_test.yml
Note: `master` is left in nbde_client_clevis.py as follows, which causes the non-inclusive language check action fails.
```
library/nbde_client_clevis.py:    """Generate a new key with the same entropy as the LUKS master key.
```
There are three ways to fix it - 1) replacing `LUKS master key` with a phrase that does not include `master` or 2) leaving `LUKS master key` as it is and applying https://github.com/get-woke/woke/pull/252 …

Add check for non-inclusive language

---

tasks/main-clevis.yml

Under certain conditions on some platforms, enabling the askpass.path service
will fail with "file not found".  Using `daemon_reload: true` makes it
work.

Use daemon_reload with askpass path service

---

library/nbde_client_clevis.py
tasks/main-clevis.yml
tests/tests_error_handling.yml

Because the nbde_client role throws the error in a block/always, the error
must be caught with rescue and rethrown.  See
https://richm.github.io/how-to-catch-and-reraise-errors-in-ansible
The sensitive field might be in a deeply nested data structure, so
iterate through the data structure.
The re-raised error is not in `ansible_failed_result` it is in
`ansible_failed_result.msg`

Fix nbde_client error handling

---

tasks/main-clevis.yml
templates/module-setup.sh.j2
templates/nbde_client-hook.sh.j2
templates/nbde_client-network-flush.j2
templates/nbde_client-network-flush.service.j2

Move files in the files directory to the templates; use the template module instead of copy for deploying them to add ansible_managed and fingerprint header.
Note: This fingerprint information is provided to help customers identify that it was generated by system roles. It may also be used for future analysis.

Use templates instead of files for ansible_managed

---

templates/nbde_client.conf
tests/tasks/check_header.yml
tests/templates/get_ansible_managed.j2
tests/tests_simple_bind.yml

Add ansible_managed header and fingerprint to dracut config file
Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See …

test: check generated files for ansible_managed, fingerprint

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-plugin-scan.yml
.github/workflows/ansible-test.yml
.github/workflows/python-unit-test.yml
.ostree/README.md
.ostree/get_ostree_data.sh
README-ostree.md

The old ansible-community ansible-lint is deprecated.  There is a
new ansible-lint github action.
The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to convert the role to collection format before running
ansible-test.
This also requires tox-lsr 3.2.1 - bump other actions to use 3.2.1
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

ci: Use supported ansible-lint action; run ansible-lint against the collection

---

tasks/clear_initrd_netcfg-dracut_module.yml
tasks/clear_initrd_netcfg-networkmanager_config.yml
tasks/main-clevis.yml
templates/NetworkManager.conf.j2
vars/AlmaLinux_8.yml
vars/AlmaLinux_9.yml
vars/CentOS_7.yml
vars/CentOS_8.yml
vars/CentOS_9.yml
vars/Fedora.yml
vars/RedHat_7.yml
vars/RedHat_8.yml
vars/RedHat_9.yml

Uses a NetworkManager config drop in file to accomplish the equivalent of the previous network flushing dracut module.
I have no idea how correct my approach is, I took the general approach from another system role I found. Nor do I know of any way to properly test this on real systems.
Closes #155

refactor: clear net config from initrd via NM config

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-plugin-scan.yml
.github/workflows/ansible-test.yml
.github/workflows/python-unit-test.yml
.yamllint.yml
tests/tests_use_existing_binding.yml

The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …

ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

---

tests/tests_simple_bind.yml

The files
- /usr/bin/nbde_client-network-flush
- /etc/systemd/system/nbde_client-network-flush.service
- /usr/lib/dracut/modules.d/60nbde_client/module-setup.sh
- /usr/lib/dracut/modules.d/60nbde_client/nbde_client-hook.sh
Are not created when using the NetworkManager implementation
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

test: some files not created by nm implementation

---

meta/main.yml
tests/vars/CentOS_10.yml
tests/vars/RedHat_10.yml
vars/AlmaLinux_10.yml
vars/CentOS_10.yml
vars/RedHat_10.yml

According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …

fix: add support for EL10

---

vars/Debian.yml

Enhancement: Adds support for Debian. However, since Debian only supports dm-crypt as a full-disk encryption method during install, support for early boot is explicitly disabled. This also prevents a dependency on NetworkManager, which is known to cause issues for some Debian-family distributions (notably Proxmox).
Reason: Needed Debian/Proxmox late-boot support
Result: Adds vars file for Debian, which will be included as OS family file.
Issue Tracker Tickets (Jira or BZ if any): N/A

chore: add debian late boot support
